/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
var aaa;
export default function Modell({ ...props }) {
  aaa = props.src;
  console.log(aaa);
  const group = useRef();
  var { nodes, materials } = useGLTF(aaa);
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body.geometry}
          material={materials.paintWhite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body_1.geometry}
          material={materials.paintRed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body_2.geometry}
          material={materials.plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body_3.geometry}
          material={materials.carTire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body_4.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body_5.geometry}
          material={materials.lightFront}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body_6.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_body_7.geometry}
          material={materials.lightBlue}
        />
      </group>
      <group position={[-0.55, 0.4, 1.57]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorLeft.geometry}
          material={materials.paintWhite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorLeft_1.geometry}
          material={materials.plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorLeft_2.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorLeft_3.geometry}
          material={materials.paintRed}
        />
      </group>
      <group position={[0.55, 0.4, 1.57]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorRight.geometry}
          material={materials.paintWhite}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorRight_1.geometry}
          material={materials.plastic}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorRight_2.geometry}
          material={materials.window}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_doorRight_3.geometry}
          material={materials.paintRed}
        />
      </group>
      <group position={[-0.3, 0.3, 0.91]} scale={[-1, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft.geometry}
          material={materials.carTire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_2.geometry}
          material={materials.plastic}
        />
      </group>
      <group
        position={[0.3, 0.3, 0.91]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft.geometry}
          material={materials.carTire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_2.geometry}
          material={materials.plastic}
        />
      </group>
      <group position={[-0.3, 0.3, -1.01]} scale={[-1, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft.geometry}
          material={materials.carTire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_2.geometry}
          material={materials.plastic}
        />
      </group>
      <group
        position={[0.3, 0.3, -1.01]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft.geometry}
          material={materials.carTire}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_1.geometry}
          material={materials._defaultMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_wheel_frontLeft_2.geometry}
          material={materials.plastic}
        />
      </group>
    </group>
  );
}

useGLTF.preload(aaa);
